[build]
  command = "npm install --legacy-peer-deps && CI=false ESLINT_NO_DEV_ERRORS=true npm run build"
  publish = "build"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  ESLINT_NO_DEV_ERRORS = "true"
