[build]
  command = "npm install --legacy-peer-deps && DISABLE_ESLINT_PLUGIN=true CI=false SKIP_PREFLIGHT_CHECK=true TSC_COMPILE_ON_ERROR=true GENERATE_SOURCEMAP=false npm run build"
  publish = "build"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  ESLINT_NO_DEV_ERRORS = "true"
  TSC_COMPILE_ON_ERROR = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_PREFLIGHT_CHECK = "true"

# SPAリダイレクトの設定 - すべてのURLをindex.htmlにリダイレクト
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
