[build]
  command = "CI=false npm install --legacy-peer-deps && npm run build"
  publish = "build"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_PREFLIGHT_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"
  GENERATE_SOURCEMAP = "false"

